
services:
  openlitespeed:
    image: litespeedtech/openlitespeed:latest
    container_name: openlitespeed
    ports:
      - "8080:80"
      - "443:443"
      - "7080:7080" # OpenLiteSpeed admin
    volumes:
      - ./html:/var/www/vhosts/${DOMAIN}/html
      - ./conf:/usr/local/lsws/conf
      - ./certs:/etc/letsencrypt
    environment:
      - OLS_DB_NAME=${DB_NAME}
      - OLS_DB_USER=${DB_USER}
      - OLS_DB_PASS=${DB_PASSWORD}
      - OLS_PHP_MEMORY_LIMIT=256M
      - OLS_PHP_UPLOAD_MAX_FILESIZE=1024M
      - OLS_PHP_POST_MAX_SIZE=1024M
    depends_on:
      - mariadb
      - traefik

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    volumes:
      - ./html/phpmyadmin:/var/www/html
    depends_on:
      - mariadb
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dev.rule=Host(`${DOMAIN}`)"
      - "traefik.http.services.dev.loadbalancer.server.port=80"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.${DOMAIN}`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin.tls.certresolver=myresolver"
    ports:
      - "8080:80"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./html:/var/www/vhosts/${DOMAIN}/html
    command: certonly --webroot -w /var/www/vhosts/${DOMAIN}/html -d ${DOMAIN} -d phpmyadmin.${DOMAIN} --email admin@${DOMAIN} --agree-tos --non-interactive

  traefik:
    image: traefik:v2.5
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:8081"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=dev@${DOMAIN}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "8081:80"
      - "443:443"
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
