version: '3.8'
services:
  # NGINX Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d   # NGINX config folder
      - ./nginx/ssl:/etc/nginx/ssl         # SSL certificates
      - ./nginx/logs:/var/log/nginx        # Logs
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME} 
    networks:
      - frontend-network
      - backend-network
    depends_on:
      - frontend
      - backend

  # Frontend Service (e.g., React, Vue)
  frontend:
    image: node:14-alpine
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: ["npm", "run", "build"]  # Or start server if SSR
    ports:
      - "${FRONTEND_PORT}:8080"  # Use the port defined in .env
    networks:
      - frontend-network

  # Backend Service (e.g., Node.js, Django, Flask)
  backend:
    image: node:14-alpine   # Change this for Django, Flask, etc.
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      - DB_HOST=mariadb
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD==${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    command: ["npm", "run", "start"]  # Or equivalent for your backend framework
    ports:
      - "${BACKEND_PORT}:8090"
    networks:
      - backend-network
    depends_on:
      - mariadb

  # MariaDB (Database)
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${TIMEZONE} 
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql   # Persistent storage for database
    networks:
      - backend-network

  # phpMyAdmin (optional)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "8081:80"  # Access phpMyAdmin at http://localhost:8081
    depends_on:
      - mariadb
    networks:
      - backend-network

# Volumes for data persistence
volumes:
  db_data:

# Networks for service separation
networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
